FROM node:12 as builder

RUN mkdir /usr/src/app

WORKDIR /usr/src/app
COPY client2/package.json /usr/src/app/package.json

RUN npm install
RUN yarn install

COPY client2 /usr/src/app

CMD ["npm", "run", "build"]


FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80
